#!/usr/bin/env bash
set -euo pipefail

version="0.2.0-test"
asset="Chowder-Apple-Silicon-${version}.app.tar.gz"
url="https://raw.githubusercontent.com/advtuning/chowder-downloads/main/${asset}"
sha256="321a747122bc234689ad6a5a20c23a8f214de4e702ec5f530bdc4692788c7b37"

[[ "$(uname -s)" == "Darwin" ]] || { echo "Chowder for macOS must be installed on a Mac." >&2; exit 1; }

is_apple_silicon() {
  local machine translated arm64_capable

  machine="$(uname -m)"
  [[ "$machine" == "arm64" ]] && return 0

  # A Terminal launched with Rosetta reports x86_64 even on Apple Silicon.
  # sysctl.proc_translated is Apple's supported way to identify that state;
  # hw.optional.arm64 is a hardware-capability fallback for other translated shells.
  translated="$(sysctl -in sysctl.proc_translated 2>/dev/null || true)"
  [[ "$translated" == "1" ]] && return 0

  arm64_capable="$(sysctl -n hw.optional.arm64 2>/dev/null || true)"
  [[ "$arm64_capable" == "1" ]] && return 0

  return 1
}

is_apple_silicon || { echo "This build requires an Apple Silicon Mac." >&2; exit 1; }

# Used only by the deterministic architecture checks in this repository.
[[ "${CHOWDER_ARCH_CHECK_ONLY:-0}" == "1" ]] && exit 0

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT

ensure_clamav() {
  local brew_bin="/opt/homebrew/bin/brew"

  if [[ ! -x "$brew_bin" ]]; then
    echo "Installing native Apple Silicon Homebrew..."
    /usr/bin/arch -arm64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  fi

  [[ -x "$brew_bin" ]] || {
    echo "Homebrew was not installed at the Apple Silicon location /opt/homebrew." >&2
    return 1
  }

  if ! "$brew_bin" list --versions clamav >/dev/null 2>&1; then
    echo "Installing ClamAV..."
    "$brew_bin" install clamav
  fi

  clamav_bin="$("$brew_bin" --prefix)/bin"
  clamscan="$clamav_bin/clamscan"
  freshclam="$clamav_bin/freshclam"
  [[ -x "$clamscan" && -x "$freshclam" ]] || {
    echo "ClamAV installation is incomplete: clamscan or freshclam is missing." >&2
    return 1
  }
}

initialize_definitions() {
  local data_root="${CHOWDER_DATA_ROOT:-$HOME/Library/Application Support/chowder}"
  local config_dir="$data_root/config"
  definitions="$data_root/database/active"
  local config="$config_dir/freshclam-installer.conf"
  local probe="$work/chowder-installer-scan-probe.txt"
  local eicar="$work/chowder-installer-eicar.com"
  local detection_output detection_status

  mkdir -p "$config_dir" "$definitions"
  printf '%s\n' \
    '# Generated by the Chowder macOS installer.' \
    "DatabaseDirectory $definitions" \
    'DatabaseMirror database.clamav.net' \
    'DNSDatabaseInfo current.cvd.clamav.net' \
    'LogVerbose no' \
    'LogTime yes' \
    'MaxAttempts 3' \
    'ConnectTimeout 30' \
    'ReceiveTimeout 60' >"$config"

  echo "Downloading current ClamAV malware definitions..."
  "$freshclam" --stdout --config-file="$config" --datadir="$definitions"

  find "$definitions" -maxdepth 1 -type f \( -name '*.cvd' -o -name '*.cld' \) -print -quit | grep -q . || {
    echo "ClamAV did not produce a usable definition database." >&2
    return 1
  }

  printf 'Chowder installer scanner verification.\n' >"$probe"
  "$clamscan" --database="$definitions" --no-summary "$probe"

  # ClamAV's own documentation uses the harmless EICAR test signature to prove that a definition
  # database can actually detect, rather than merely load. The temporary file is removed with $work.
  printf '%s' 'X5O!P%@AP[4\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*' >"$eicar"
  set +e
  detection_output="$("$clamscan" --database="$definitions" --no-summary "$eicar" 2>&1)"
  detection_status=$?
  set -e
  [[ "$detection_status" == "1" && "$detection_output" == *"FOUND"* ]] || {
    echo "ClamAV loaded the database but did not detect its standard harmless test signature." >&2
    printf '%s\n' "$detection_output" >&2
    return 1
  }

  clamav_version="$("$clamscan" --database="$definitions" --version | head -n 1)"
}

echo "Downloading Chowder ${version}..."
curl -fL --retry 3 --output "$work/$asset" "$url"
printf '%s  %s\n' "$sha256" "$work/$asset" | shasum -a 256 -c -
tar -xzf "$work/$asset" -C "$work"

binary="$work/Chowder.app/Contents/MacOS/chowder-macos"
[[ -f "$binary" ]] || { echo "The Chowder application bundle is incomplete." >&2; exit 1; }
chmod 0755 "$binary"
file "$binary" | grep -Eq 'Mach-O 64-bit .*arm64' || { echo "The Chowder executable is not Apple Silicon." >&2; exit 1; }

ensure_clamav
initialize_definitions

install_root="${CHOWDER_INSTALL_ROOT:-$HOME/Applications}"
target="$install_root/Chowder.app"
process_path="$target/Contents/MacOS/chowder-macos"
mkdir -p "$install_root"

# This local test build is not Developer ID signed yet. Apply an ad-hoc signature only after the
# pinned archive and native architecture have been verified.
/usr/bin/codesign --force --deep --sign - "$work/Chowder.app"
/usr/bin/codesign --verify --deep --strict "$work/Chowder.app"

if [[ -e "$target" ]]; then
  /usr/bin/osascript -e 'tell application id "com.chowderav.Chowder" to quit' 2>/dev/null || true
  for _ in {1..20}; do
    pgrep -f "$process_path" >/dev/null 2>&1 || break
    sleep 0.25
  done
  pgrep -f "$process_path" >/dev/null 2>&1 && {
    echo "The running Chowder application did not close; installation was not replaced." >&2
    exit 1
  }
  mv "$target" "$install_root/Chowder.app.backup-$(date +%Y%m%d%H%M%S)"
fi
/usr/bin/ditto "$work/Chowder.app" "$target"
/usr/bin/xattr -dr com.apple.quarantine "$target" 2>/dev/null || true
/usr/bin/codesign --verify --deep --strict "$target"

/usr/bin/caffeinate -u -t 15 >/dev/null 2>&1 &
open -n "$target"
for _ in {1..20}; do
  pgrep -f "$process_path" >/dev/null 2>&1 && break
  sleep 0.5
done
launch_pid="$(pgrep -f "$process_path" | tail -n 1 || true)"
[[ -n "$launch_pid" ]] || {
  echo "Chowder was installed but its GUI did not remain running." >&2
  exit 1
}

echo "Chowder ${version} installed in $target."
echo "ClamAV ready: $clamav_version"
echo "Definitions ready in $definitions."
echo "Clean-file and harmless EICAR detection self-tests passed."
echo "Chowder GUI launched as process $launch_pid."
